name: test Phoo
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - name: test files
        run: |
          for file in **/*.test.ph
          do
            echo "--------------------------$file--------------------------"
            node --experimental-modules test/test_runner.js $file
          done
        