name: test Phoo
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - name: test files
        run: |
          python3 - <<EOF
          import sys, os, glob
          files = glob.glob('**/*.test.ph')
          if len(files) == 0:
            print('(No tests)')
            sys.exit(0)
          for file in files:
            print('-' * 30, file, '-' * 30)
            code = os.system('node --experimental-modules test/test_runner.js ' + file)
            if code > 0:
              sys.exit(1)
          EOF
        